sudo: false

os:
- linux

language: python

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

install:
- pip install -r requirements.txt
- pip install pytest-cov
- pip install .

script:
- python -m pytest -v

cache:
  directories:
  - "$HOME/.cache/pip"

deploy:
  provider: pypi
  user: akaszynski
  distributions: sdist
  on:
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
    tags: true
  password: $PYPI_PASSWORD

notifications:
  email: false