sudo: required

dist: xenial

os:
  - linux

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'

addons:
  apt:
    packages:
      - xvfb

env:
  global:
    # Doctr deploy key for vtkiorg/vtki-docs
    - secure: "IIlZXKvOLypbEMEvIdnlM97sKMGboXDVQMS6ElGB5ZF15flaB7ko3wFTwROYggUFYJQoENnw5lJVdvmg7/VXbCSwdZfjdcCJ6P2avAxr4dj7W/lTn5WWztwYPelt/6Mkkjei/tfgCLwqF3UA+oT+JJDvRusDTSN3jI9t6wBQCNbQL/cZpQaGiupBeoUDrsRqxCBBys163BVbQi+qP+DKoOJIWAivj11BfSiJ02wnSJMODYD6Fmu8VMHhX6WdUm00yL/olygmV1P/jDikwCHRZFXkrSH7IUldzvOODS1rtLwSXBXJSt3FvtBJFUWFlSEPdTed4A4oUvT2q60AMVwyUcXkc+vuHeFLQz5Yp/aypBXuBt3FWL3/VxFNliSK2o5bmiX4v1h3hev+wFIOrvL8anlgK9KzMh7KZ2GANv113uHYYJDxOUryddzrtoITEMsHD62i+eQDJu7Gx9ZFV9thk7gAMsQ1hVoyXhl3cNp5lZP+QEpKNcuX0o8+134sUQSiFTuzoOW3/A1Cc0d1p2lBKumSH3uioP+LuMMAuDAOGBUu69JLak44QUnAzpj377alR1G0SkB2kprWwwSMtqyv1Md0/G/3SZMIAgcybnM43cFJIdBodDVMWD26EySJB3/Tzd7vjRlzWAu3Nb359sWQFAnrSv9q4hLpumLVQtJxFF4="

before_script: # configure a headless display to test plot generation
  - export DISPLAY=:99.0
  - which Xvfb
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # - ls -l /etc/init.d/
  # - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - pip install -r requirements.txt
  - pip install -r requirements_docs.txt
  - pip install pytest-cov
  - pip install codecov
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then
      pip install -r requirements_test.txt
      pip install -U doctr
    fi
  - pip install -e .
  - which python
  - python -c "import vtk; print(vtk.VTK_VERSION)"
  - python -c "import imageio; imageio.plugins.ffmpeg.download()"
  - pip list

script:
  # Run the test suite and generate coverage report
  - pytest -v --cov vtki
  # Run all code examples in the docstrings
  - pytest -v --doctest-modules vtki
  - |  # report code coverage
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      codecov
    fi
  # Now make sure notebooks are running
  # TODO: add below: pytest -v --nbval-lax --current-env --disable-warnings tests/*.ipynb;
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then
      pytest -v --nbval-lax --current-env --disable-warnings notebooks/*.ipynb;
    fi
  # And test the documentation
  - cd ./docs/
  - make html
  - make doctest
  - make html
  # now deploy the docs # TODO: ensure only on the master branch!
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      set -e;
      doctr deploy --built-docs _build/html/ --deploy-repo vtkiorg/vtki-docs docs/;
    fi
  # And then clean up and changes from running examples with fileio
  - cd ..
  - git reset --hard # removes staged and working directory changes

cache:
  directories:
  - "$HOME/.cache/pip"

deploy:
  provider: pypi
  user: akaszynski
  distributions: sdist
  on:
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
    tags: true
  password: $PYPI_PASSWORD

notifications:
  email: false
